apiVersion: v1
kind: Service
metadata:
  name: refinement-bot
  labels:
    app: refinement-bot
spec:
  selector:
    app: refinement-bot
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
